### ISSUE TITLE
New tile map

### ISSUE THREAD

**Issue by photodiode** [Loonride/cppcraft#1]
Hi, neat project!
I was bored and for fun just made a new tile map, I hope you don't mind.
No hard feelings if you don't use it ;)
![blocks](https://user-images.githubusercontent.com/16804570/41186449-ad1d036a-6bd1-11e8-9299-7aa7155c8d57.png)

**Comment by knagaitsev** [comment]
Thanks, I appreciate it! Looks much better than my own attempt.

![image](https://user-images.githubusercontent.com/22580625/41186773-1822d736-6b62-11e8-9e88-e0aeabddd365.png)

**Comment by photodiode** [comment]
Thank you!
I saw that the cobble stone and leaves could be better so I tried doing a revision.
![blocks](https://user-images.githubusercontent.com/16804570/41189392-1a55ef6a-6c08-11e8-9199-9f3c6fa3a0b0.png)

Edit: Sky color suggestion: 77, 197, 255 (#4dc5ff)
